import type { ProviderMovieDetail } from "./types";

/**
 * Offline catalog used by the mock provider when no TMDB credentials are
 * configured. It is a small development fixture, not a movie master database.
 */
export const MOCK_CATALOG: ProviderMovieDetail[] = [
  {
    providerId: "m-arrival",
    title: "Arrival",
    originalTitle: "Arrival",
    releaseDate: "2016-11-11",
    overview:
      "A linguist is recruited to communicate with extraterrestrial visitors, and her understanding of language reshapes her perception of time and loss.",
    popularity: 62,
    voteAverage: 7.6,
    voteCount: 18000,
    genres: ["Science Fiction", "Drama", "Mystery"],
    runtime: 116,
    country: "US",
    language: "en",
    director: "Denis Villeneuve",
    cast: ["Amy Adams", "Jeremy Renner", "Forest Whitaker"],
    keywords: ["first contact", "linguistics", "time", "grief", "philosophical", "quiet"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-blade-runner-2049",
    title: "Blade Runner 2049",
    releaseDate: "2017-10-04",
    overview:
      "A replicant blade runner uncovers a secret that could shatter what remains of society, and searches for a man who disappeared thirty years ago.",
    popularity: 71,
    voteAverage: 7.6,
    voteCount: 14000,
    genres: ["Science Fiction", "Drama", "Mystery"],
    runtime: 164,
    country: "US",
    language: "en",
    director: "Denis Villeneuve",
    cast: ["Ryan Gosling", "Harrison Ford", "Ana de Armas"],
    keywords: ["dystopia", "replicant", "neo-noir", "identity", "visual", "slow burn"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-dune",
    title: "Dune",
    releaseDate: "2021-09-15",
    overview:
      "A noble family is drawn into a war for control of the desert planet Arrakis and the most valuable resource in the known universe.",
    popularity: 90,
    voteAverage: 7.8,
    voteCount: 12000,
    genres: ["Science Fiction", "Adventure"],
    runtime: 155,
    country: "US",
    language: "en",
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Rebecca Ferguson", "Oscar Isaac"],
    keywords: ["desert", "epic", "worldbuilding", "prophecy", "spice", "politics"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-perfect-days",
    title: "PERFECT DAYS",
    originalTitle: "パーフェクト デイズ",
    releaseDate: "2023-12-22",
    overview:
      "A Tokyo toilet cleaner lives a quiet, ordered life of small rituals, cassette tapes and light through leaves.",
    popularity: 40,
    voteAverage: 7.9,
    voteCount: 1400,
    genres: ["Drama"],
    runtime: 124,
    country: "JP",
    language: "ja",
    director: "Wim Wenders",
    cast: ["Koji Yakusho", "Tokio Emoto", "Arisa Nakano"],
    keywords: ["slice of life", "tokyo", "quiet", "routine", "melancholy", "contemplative"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-in-the-mood-for-love",
    title: "In the Mood for Love",
    originalTitle: "花樣年華",
    releaseDate: "2000-09-29",
    overview:
      "Two neighbours discover their spouses are having an affair and slowly, painfully fall for each other.",
    popularity: 35,
    voteAverage: 8.1,
    voteCount: 4200,
    genres: ["Romance", "Drama"],
    runtime: 98,
    country: "HK",
    language: "zh",
    director: "Wong Kar-wai",
    cast: ["Tony Leung", "Maggie Cheung"],
    keywords: ["longing", "restraint", "1960s", "visual", "melancholy", "romance"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-parasite",
    title: "Parasite",
    originalTitle: "기생충",
    releaseDate: "2019-05-30",
    overview:
      "A poor family schemes to become employed by a wealthy household, until an unexpected discovery upends everything.",
    popularity: 95,
    voteAverage: 8.5,
    voteCount: 17000,
    genres: ["Thriller", "Drama", "Comedy"],
    runtime: 132,
    country: "KR",
    language: "ko",
    director: "Bong Joon-ho",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
    keywords: ["class", "satire", "twist", "dark humor", "suspense", "social"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-spirited-away",
    title: "Spirited Away",
    originalTitle: "千と千尋の神隠し",
    releaseDate: "2001-07-20",
    overview:
      "A girl wanders into a world of spirits and must work in a bathhouse to free her parents.",
    popularity: 88,
    voteAverage: 8.5,
    voteCount: 16000,
    genres: ["Animation", "Fantasy", "Family"],
    runtime: 125,
    country: "JP",
    language: "ja",
    director: "Hayao Miyazaki",
    cast: ["Rumi Hiiragi", "Miyu Irino"],
    keywords: ["spirits", "coming of age", "worldbuilding", "magic", "wonder"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-mad-max-fury-road",
    title: "Mad Max: Fury Road",
    releaseDate: "2015-05-13",
    overview: "In a post-apocalyptic wasteland, a woman rebels against a tyrant in search of her homeland.",
    popularity: 84,
    voteAverage: 7.6,
    voteCount: 21000,
    genres: ["Action", "Adventure", "Science Fiction"],
    runtime: 120,
    country: "AU",
    language: "en",
    director: "George Miller",
    cast: ["Tom Hardy", "Charlize Theron", "Nicholas Hoult"],
    keywords: ["chase", "desert", "practical effects", "kinetic", "post-apocalyptic"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-whiplash",
    title: "Whiplash",
    releaseDate: "2014-10-10",
    overview: "A young drummer enrols at a conservatory where a ruthless instructor pushes him past his limits.",
    popularity: 70,
    voteAverage: 8.4,
    voteCount: 14000,
    genres: ["Drama", "Music"],
    runtime: 106,
    country: "US",
    language: "en",
    director: "Damien Chazelle",
    cast: ["Miles Teller", "J.K. Simmons"],
    keywords: ["jazz", "obsession", "mentor", "tension", "ambition"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-her",
    title: "Her",
    releaseDate: "2013-12-18",
    overview: "A lonely writer develops a relationship with an operating system designed to meet his every need.",
    popularity: 66,
    voteAverage: 8.0,
    voteCount: 13000,
    genres: ["Romance", "Drama", "Science Fiction"],
    runtime: 126,
    country: "US",
    language: "en",
    director: "Spike Jonze",
    cast: ["Joaquin Phoenix", "Scarlett Johansson", "Amy Adams"],
    keywords: ["loneliness", "artificial intelligence", "near future", "intimacy", "melancholy"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-2001",
    title: "2001: A Space Odyssey",
    releaseDate: "1968-04-02",
    overview: "Humanity finds a mysterious monolith and sets off on a voyage to Jupiter with the sentient computer HAL.",
    popularity: 55,
    voteAverage: 8.3,
    voteCount: 12000,
    genres: ["Science Fiction", "Mystery", "Adventure"],
    runtime: 149,
    country: "GB",
    language: "en",
    director: "Stanley Kubrick",
    cast: ["Keir Dullea", "Gary Lockwood"],
    keywords: ["space", "evolution", "ambiguous", "philosophical", "experimental", "slow"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-ex-machina",
    title: "Ex Machina",
    releaseDate: "2015-01-21",
    overview: "A programmer is invited to administer the Turing test to an intelligent humanoid robot.",
    popularity: 64,
    voteAverage: 7.6,
    voteCount: 12000,
    genres: ["Science Fiction", "Thriller", "Drama"],
    runtime: 108,
    country: "GB",
    language: "en",
    director: "Alex Garland",
    cast: ["Domhnall Gleeson", "Alicia Vikander", "Oscar Isaac"],
    keywords: ["artificial intelligence", "manipulation", "chamber piece", "tension", "philosophical"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-annihilation",
    title: "Annihilation",
    releaseDate: "2018-02-22",
    overview: "A biologist joins an expedition into a quarantined zone where the laws of nature do not apply.",
    popularity: 58,
    voteAverage: 6.9,
    voteCount: 9000,
    genres: ["Science Fiction", "Horror", "Mystery"],
    runtime: 115,
    country: "US",
    language: "en",
    director: "Alex Garland",
    cast: ["Natalie Portman", "Jennifer Jason Leigh", "Oscar Isaac"],
    keywords: ["mutation", "surreal", "dread", "ambiguous", "visual"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-moon",
    title: "Moon",
    releaseDate: "2009-06-12",
    overview: "A lone worker nearing the end of a three-year contract on the Moon starts to unravel.",
    popularity: 38,
    voteAverage: 7.5,
    voteCount: 6000,
    genres: ["Science Fiction", "Drama", "Mystery"],
    runtime: 97,
    country: "GB",
    language: "en",
    director: "Duncan Jones",
    cast: ["Sam Rockwell", "Kevin Spacey"],
    keywords: ["isolation", "clone", "identity", "quiet", "low budget"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-solaris",
    title: "Solaris",
    originalTitle: "Солярис",
    releaseDate: "1972-03-20",
    overview: "A psychologist is sent to a space station orbiting a planet that materialises human memories.",
    popularity: 26,
    voteAverage: 8.0,
    voteCount: 3000,
    genres: ["Science Fiction", "Drama", "Mystery"],
    runtime: 167,
    country: "SU",
    language: "ru",
    director: "Andrei Tarkovsky",
    cast: ["Donatas Banionis", "Natalya Bondarchuk"],
    keywords: ["memory", "grief", "philosophical", "slow", "experimental", "ambiguous"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-grand-budapest",
    title: "The Grand Budapest Hotel",
    releaseDate: "2014-02-26",
    overview: "A legendary concierge and his protégé become entangled in the theft of a priceless painting.",
    popularity: 74,
    voteAverage: 8.0,
    voteCount: 15000,
    genres: ["Comedy", "Adventure", "Drama"],
    runtime: 99,
    country: "US",
    language: "en",
    director: "Wes Anderson",
    cast: ["Ralph Fiennes", "Tony Revolori", "Saoirse Ronan"],
    keywords: ["symmetry", "whimsical", "caper", "stylised", "witty"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-la-la-land",
    title: "La La Land",
    releaseDate: "2016-12-09",
    overview: "A jazz pianist and an aspiring actress fall in love while pursuing their dreams in Los Angeles.",
    popularity: 80,
    voteAverage: 7.9,
    voteCount: 16000,
    genres: ["Romance", "Drama", "Music"],
    runtime: 128,
    country: "US",
    language: "en",
    director: "Damien Chazelle",
    cast: ["Ryan Gosling", "Emma Stone"],
    keywords: ["musical", "dreams", "bittersweet", "color", "jazz"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-past-lives",
    title: "Past Lives",
    releaseDate: "2023-06-02",
    overview: "Two childhood friends reunite in New York decades later and confront the lives they did not live.",
    popularity: 45,
    voteAverage: 7.8,
    voteCount: 2200,
    genres: ["Romance", "Drama"],
    runtime: 105,
    country: "US",
    language: "en",
    director: "Celine Song",
    cast: ["Greta Lee", "Teo Yoo", "John Magaro"],
    keywords: ["longing", "diaspora", "quiet", "fate", "melancholy"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-everything-everywhere",
    title: "Everything Everywhere All at Once",
    releaseDate: "2022-03-25",
    overview: "A laundromat owner is swept into a multiversal adventure to save existence.",
    popularity: 92,
    voteAverage: 7.8,
    voteCount: 13000,
    genres: ["Action", "Comedy", "Science Fiction"],
    runtime: 139,
    country: "US",
    language: "en",
    director: "Daniel Kwan",
    cast: ["Michelle Yeoh", "Ke Huy Quan", "Stephanie Hsu"],
    keywords: ["multiverse", "family", "absurd", "kinetic", "emotional", "experimental"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-the-social-network",
    title: "The Social Network",
    releaseDate: "2010-10-01",
    overview: "The founding of Facebook and the lawsuits that followed.",
    popularity: 60,
    voteAverage: 7.7,
    voteCount: 11000,
    genres: ["Drama", "History"],
    runtime: 120,
    country: "US",
    language: "en",
    director: "David Fincher",
    cast: ["Jesse Eisenberg", "Andrew Garfield", "Justin Timberlake"],
    keywords: ["dialogue heavy", "ambition", "betrayal", "fast paced", "true story"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-se7en",
    title: "Se7en",
    releaseDate: "1995-09-22",
    overview: "Two detectives hunt a serial killer who uses the seven deadly sins as his motif.",
    popularity: 78,
    voteAverage: 8.4,
    voteCount: 19000,
    genres: ["Crime", "Thriller", "Mystery"],
    runtime: 127,
    country: "US",
    language: "en",
    director: "David Fincher",
    cast: ["Brad Pitt", "Morgan Freeman", "Kevin Spacey"],
    keywords: ["serial killer", "dark", "rain", "grim", "investigation"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-hereditary",
    title: "Hereditary",
    releaseDate: "2018-06-08",
    overview: "A family unravels after the death of their secretive grandmother.",
    popularity: 68,
    voteAverage: 7.3,
    voteCount: 9000,
    genres: ["Horror", "Drama", "Mystery"],
    runtime: 127,
    country: "US",
    language: "en",
    director: "Ari Aster",
    cast: ["Toni Collette", "Alex Wolff", "Milly Shapiro"],
    keywords: ["grief", "dread", "occult", "dark", "slow burn"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-your-name",
    title: "Your Name.",
    originalTitle: "君の名は。",
    releaseDate: "2016-08-26",
    overview: "Two teenagers discover they are swapping bodies across space and time.",
    popularity: 86,
    voteAverage: 8.5,
    voteCount: 11000,
    genres: ["Animation", "Romance", "Fantasy"],
    runtime: 106,
    country: "JP",
    language: "ja",
    director: "Makoto Shinkai",
    cast: ["Ryunosuke Kamiki", "Mone Kamishiraishi"],
    keywords: ["body swap", "fate", "emotional", "visual", "comet"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-drive-my-car",
    title: "Drive My Car",
    originalTitle: "ドライブ・マイ・カー",
    releaseDate: "2021-08-20",
    overview: "A grieving stage director forms a bond with the young woman assigned to drive his car.",
    popularity: 33,
    voteAverage: 7.5,
    voteCount: 1800,
    genres: ["Drama"],
    runtime: 179,
    country: "JP",
    language: "ja",
    director: "Ryusuke Hamaguchi",
    cast: ["Hidetoshi Nishijima", "Toko Miura"],
    keywords: ["grief", "theatre", "long", "quiet", "dialogue heavy", "contemplative"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-interstellar",
    title: "Interstellar",
    releaseDate: "2014-11-05",
    overview: "Explorers travel through a wormhole in search of a new home for humanity.",
    popularity: 96,
    voteAverage: 8.4,
    voteCount: 34000,
    genres: ["Science Fiction", "Adventure", "Drama"],
    runtime: 169,
    country: "US",
    language: "en",
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    keywords: ["space", "time dilation", "family", "epic", "emotional", "science"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-inception",
    title: "Inception",
    releaseDate: "2010-07-15",
    overview: "A thief who steals corporate secrets through dream-sharing is given the inverse task of planting an idea.",
    popularity: 98,
    voteAverage: 8.4,
    voteCount: 36000,
    genres: ["Action", "Science Fiction", "Thriller"],
    runtime: 148,
    country: "US",
    language: "en",
    director: "Christopher Nolan",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    keywords: ["dreams", "heist", "complex", "layered", "puzzle"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-spider-verse",
    title: "Spider-Man: Into the Spider-Verse",
    releaseDate: "2018-12-06",
    overview: "Miles Morales becomes Spider-Man and meets heroes from other dimensions.",
    popularity: 89,
    voteAverage: 8.4,
    voteCount: 14000,
    genres: ["Animation", "Action", "Adventure"],
    runtime: 117,
    country: "US",
    language: "en",
    director: "Bob Persichetti",
    cast: ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld"],
    keywords: ["multiverse", "coming of age", "stylised", "kinetic", "fun"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-paddington-2",
    title: "Paddington 2",
    releaseDate: "2017-11-10",
    overview: "Paddington takes odd jobs to buy a present, then is framed for a crime he did not commit.",
    popularity: 52,
    voteAverage: 7.7,
    voteCount: 4500,
    genres: ["Family", "Comedy", "Adventure"],
    runtime: 103,
    country: "GB",
    language: "en",
    director: "Paul King",
    cast: ["Ben Whishaw", "Hugh Grant", "Sally Hawkins"],
    keywords: ["heartwarming", "comfort", "gentle", "humor", "family"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-little-forest",
    title: "Little Forest: Summer/Autumn",
    originalTitle: "リトル・フォレスト 夏・秋",
    releaseDate: "2014-08-30",
    overview: "A young woman returns to her rural village and lives through the seasons by cooking what she grows.",
    popularity: 20,
    voteAverage: 7.4,
    voteCount: 400,
    genres: ["Drama"],
    runtime: 111,
    country: "JP",
    language: "ja",
    director: "Junichi Mori",
    cast: ["Ai Hashimoto"],
    keywords: ["food", "seasons", "healing", "slow", "comfort", "rural"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-the-lighthouse",
    title: "The Lighthouse",
    releaseDate: "2019-10-18",
    overview: "Two lighthouse keepers descend into madness on a remote New England island.",
    popularity: 47,
    voteAverage: 7.4,
    voteCount: 6000,
    genres: ["Horror", "Drama", "Fantasy"],
    runtime: 109,
    country: "US",
    language: "en",
    director: "Robert Eggers",
    cast: ["Robert Pattinson", "Willem Dafoe"],
    keywords: ["madness", "black and white", "experimental", "dark", "chamber piece"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-portrait-lady-on-fire",
    title: "Portrait of a Lady on Fire",
    originalTitle: "Portrait de la jeune fille en feu",
    releaseDate: "2019-09-18",
    overview: "A painter is commissioned to paint the wedding portrait of a young woman on a remote island.",
    popularity: 42,
    voteAverage: 8.1,
    voteCount: 3300,
    genres: ["Romance", "Drama", "History"],
    runtime: 122,
    country: "FR",
    language: "fr",
    director: "Céline Sciamma",
    cast: ["Noémie Merlant", "Adèle Haenel"],
    keywords: ["painting", "longing", "restraint", "visual", "quiet", "period"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-mission-impossible-fallout",
    title: "Mission: Impossible — Fallout",
    releaseDate: "2018-07-25",
    overview: "Ethan Hunt races to recover stolen plutonium before it is used.",
    popularity: 82,
    voteAverage: 7.4,
    voteCount: 9500,
    genres: ["Action", "Thriller", "Adventure"],
    runtime: 147,
    country: "US",
    language: "en",
    director: "Christopher McQuarrie",
    cast: ["Tom Cruise", "Henry Cavill", "Rebecca Ferguson"],
    keywords: ["stunts", "spy", "chase", "kinetic", "blockbuster"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-tokyo-story",
    title: "Tokyo Story",
    originalTitle: "東京物語",
    releaseDate: "1953-11-03",
    overview: "An elderly couple visit their grown children in Tokyo and find them too busy to care.",
    popularity: 22,
    voteAverage: 8.2,
    voteCount: 1500,
    genres: ["Drama", "Family"],
    runtime: 136,
    country: "JP",
    language: "ja",
    director: "Yasujiro Ozu",
    cast: ["Chishu Ryu", "Chieko Higashiyama"],
    keywords: ["family", "quiet", "melancholy", "slow", "classic", "restraint"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-the-handmaiden",
    title: "The Handmaiden",
    originalTitle: "아가씨",
    releaseDate: "2016-06-01",
    overview: "A con man plots to seduce a Japanese heiress with the help of a pickpocket hired as her maid.",
    popularity: 57,
    voteAverage: 8.1,
    voteCount: 5000,
    genres: ["Thriller", "Romance", "Drama"],
    runtime: 145,
    country: "KR",
    language: "ko",
    director: "Park Chan-wook",
    cast: ["Kim Min-hee", "Kim Tae-ri", "Ha Jung-woo"],
    keywords: ["twist", "erotic", "period", "visual", "deception"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-first-cow",
    title: "First Cow",
    releaseDate: "2020-03-06",
    overview: "A cook and a Chinese immigrant start a business selling fried cakes in 1820s Oregon.",
    popularity: 18,
    voteAverage: 7.1,
    voteCount: 900,
    genres: ["Drama", "Western"],
    runtime: 122,
    country: "US",
    language: "en",
    director: "Kelly Reichardt",
    cast: ["John Magaro", "Orion Lee"],
    keywords: ["friendship", "slow", "quiet", "frontier", "gentle"],
    posterPath: undefined,
    backdropPath: undefined,
  },
  {
    providerId: "m-oldboy",
    title: "Oldboy",
    originalTitle: "올드보이",
    releaseDate: "2003-11-21",
    overview: "A man imprisoned for fifteen years without explanation is released and given five days to find his captor.",
    popularity: 63,
    voteAverage: 8.3,
    voteCount: 8000,
    genres: ["Thriller", "Action", "Mystery"],
    runtime: 120,
    country: "KR",
    language: "ko",
    director: "Park Chan-wook",
    cast: ["Choi Min-sik", "Yoo Ji-tae"],
    keywords: ["revenge", "twist", "dark", "violent", "shocking"],
    posterPath: undefined,
    backdropPath: undefined,
  },
];
